### ISSUE TITLE
node-role.kubernetes.io/master -> node-role.kubernetes.io/control-plane

### ISSUE THREAD

**Issue by rdxmb** [geerlingguy/ansible-role-kubernetes#104]
> Please adapt your tooling built on top of kubeadm to use the "node-role.kubernetes.io/control-plane" label.
> The taint applied to control-plane nodes "node-role.kubernetes.io/master:NoSchedule" is now deprecated and will be removed in a future release after a GA deprecation period. 
> Apply toleration for a new, future taint "node-role.kubernetes.io/control-plane:NoSchedule" to the kubeadm CoreDNS / kube-dns managed manifests. Note that this taint is not yet applied to kubeadm control-plane nodes.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#no-really-you-must-read-this-before-you-upgrade

**Comment by geerlingguy** [comment]
What is this in relation to?

**Comment by rdxmb** [comment]
https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/tasks/master-setup.yml#L66

**Comment by rdxmb** [comment]
```
# kubectl get nodes eins -o yaml | grep -1 NoSchedule
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane

```
kubeadm version:  v1.20.6

**Comment by geerlingguy** [comment]
@rdxmb - Ah, thanks!

**Comment by geerlingguy** [comment]
@rdxmb - Just merged the other major PR (config change)—would you like to take a stab at cleaning this up now?

**Comment by rdxmb** [comment]
hm, 

1. whats the goal here? Use both of the labels? Or only one of them? 
2. What about the comment in https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/tasks/master-setup.yml#L79 We should fix this in one step.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-kubernetes/pull/126 — this will be a breaking change in the next major release of the role.
