### ISSUE TITLE
Ubuntu 21.04: Fail to add Kubernetes repository

### ISSUE THREAD

**Issue by sharon-amir** [geerlingguy/ansible-role-kubernetes#108]
13:03:52  TASK [geerlingguy.kubernetes : Add Kubernetes repository.] *********************
13:03:52  
13:03:52  fatal: [master]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu hirsute Release' does not have a Release file."}

**Comment by geerlingguy** [comment]
Note that my roles are only tested against LTS versions of Ubuntu, and it's possible there's no repository from Kubernetes for 21.04 either (I don't know if it targets short term releases).
