### ISSUE TITLE
No kubeconfig in ~/.kube

### ISSUE THREAD

**Issue by noranraskin** [geerlingguy/ansible-role-kubernetes#117]
The task `TASK [geerlingguy.kubernetes : Symlink the kubectl admin.conf to ~/.kube/conf.]` shows status `OK`, yet there's no `config` file in `~/.kube`.
However, when I run the role again with `become: false` it does work.

This happened on Ubuntu 20.04.3 LTS (Focal Fossa)
Ansible version: 2.12.1
Python version: 3.8.10

**Comment by geerlingguy** [comment]
Can you look in the root account's home directory? (possibly `/root/.kube`?)

**Comment by noranraskin** [comment]
Oh yeah there it is!

**Comment by noranraskin** [comment]
What do you think of my PR?
Didn't know if there's a way to change the user in a running playbook, but this works too.
