### ISSUE TITLE
APT ignores version pinning on Ubuntu

### ISSUE THREAD

**Issue by robin-tribe29** [geerlingguy/ansible-role-kubernetes#124]
I am aware, that this is probably not an issue of this role, but I cannot get a hold of it.
When running this role against from a template deployed Ubuntu 20.04 and 22.04, the Kubernetes tools (kubelet, kubeadm, etc.) are installed in the most recent stable version (1.24.2 at time of writing). This causes the role to fail, when initializing the cluster.
If I try to "upgrade" the tools interactively, they get downgraded to the pinned version.

I am at a loss here. Does anyone have an idea, where to look next, or what might be causing this?

Thanks in advance!

**Comment by robin-tribe29** [comment]
We are not using the patch level, we just specify `kubernetes_version: 1.23` but still the binaries are installed with version `1.24`.
But thanks for the input!

**Comment by jkinred** [comment]
> We are not using the patch level, we just specify `kubernetes_version: 1.23` but still the binaries are installed with version `1.24`. But thanks for the input!

Using the variables as above should still have the same outcome of installing the versions you want.

**Comment by robin-tribe29** [comment]
The reason for this was the following issue in Ansible Core: https://github.com/ansible/ansible/issues/77969.
Closing this issue as it was something upstream and nothing in the role.
Thanks for your help @jkinred!
