### ISSUE TITLE
User "system:anonymous" cannot get resource "configmaps" in API group

### ISSUE THREAD

**Issue by wonderphil** [geerlingguy/ansible-role-kubernetes#142]
Hi

I just tried using your role and ran into an issue when trying to join nodes to the cluster:

```
Failed to request cluster-info, will try again: 
    configmaps "cluster-info" is forbidden: 
    User "system:anonymous" cannot get resource "configmaps" in API group "" 
    in the namespace "kube-public"
```

Wondering if you had seen this before and know what I am doing wrong, I am using pretty much all the default vars; the only ones that I have changed are:

```
kubernetes_config_kubelet_configuration:
    cgroupDriver: systemd
kubernetes_allow_pods_on_control_plane: false
kubernetes_pod_network: 10.50.0.0/16
```

**Comment by bart-roos** [comment]
I had the same issue. Running `sudo kubeadm reset` on all nodes and trying again solved this issue for me.
