### ISSUE TITLE
Ubuntu 22.04 needs to Forward IPv4 and letting iptables see bridged traffic

### ISSUE THREAD

**Issue by dkirrane** [geerlingguy/ansible-role-kubernetes#146]
I'm using latest but for Ubuntu 22.04 I had to follow these steps first to get this Ansible role to work:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic

```
  - name: geerlingguy.kubernetes
    version: 7.1.2
```

**Comment by bjensen** [comment]
I can confirm this is an issue on a brand new install on 22.04 LTS

**Comment by rdxmb** [comment]
@dkirrane this seems strange to me, as https://github.com/geerlingguy/ansible-role-kubernetes/blob/7.1.2/tasks/sysctl-setup.yml should fix this.

Cannot reproduce this on master, Ubuntu 22.04.2 LTS
