### ISSUE TITLE
Changes to the location of Linux packages for Kubernetes

### ISSUE THREAD

**Issue by dsegurag** [geerlingguy/ansible-role-kubernetes#149]
Hi,

I just saw this message in the Kubernetes website:

> The legacy Linux package repositories (apt.kubernetes.io and yum.kubernetes.io)
> have been deprecated and will be frozen starting from September 13, 2023.
> Please read our [announcement](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/) for more details.

![image](https://github.com/geerlingguy/ansible-role-kubernetes/assets/21098646/c6e02098-7f87-4d17-b696-f7f8be36c348)

**Comment by rdxmb** [comment]
This freeze is kind of strange, as `kubeadm 1.25.15` is missing in the old packages. When upgrading from 1.24:

```
Note: Before you can perform this upgrade, you have to update kubeadm to v1.25.15.
```

but

```
# apt list kubeadm -a | grep 1.25

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

kubeadm/kubernetes-xenial,now 1.25.14-00 amd64 [installed]
kubeadm/kubernetes-xenial 1.25.13-00 amd64
kubeadm/kubernetes-xenial 1.25.12-00 amd64
kubeadm/kubernetes-xenial 1.25.11-00 amd64
kubeadm/kubernetes-xenial 1.25.10-00 amd64
kubeadm/kubernetes-xenial 1.25.9-00 amd64
kubeadm/kubernetes-xenial 1.25.8-00 amd64
kubeadm/kubernetes-xenial 1.25.7-00 amd64
kubeadm/kubernetes-xenial 1.25.6-00 amd64
kubeadm/kubernetes-xenial 1.25.5-00 amd64
kubeadm/kubernetes-xenial 1.25.4-00 amd64
kubeadm/kubernetes-xenial 1.25.3-00 amd64
kubeadm/kubernetes-xenial 1.25.2-00 amd64
kubeadm/kubernetes-xenial 1.25.1-00 amd64
kubeadm/kubernetes-xenial 1.25.0-00 amd64
```

so we should fix this.
