### ISSUE TITLE
ansible-lint and molecule/default

### ISSUE THREAD

**Issue by psztoch** [geerlingguy/ansible-role-kubernetes#155]
Folder molecule/default is problematic for ansible-lint. Please fix it.

**Comment by geerlingguy** [comment]
Er, what?

If that's an issue, then ansible-lint has a bug. Is there some change record that says molecule can't be used or something?

My tests are passing just fine: https://github.com/geerlingguy/ansible-role-kubernetes/actions/runs/8166910041/job/22326442353
