### ISSUE TITLE
kubernetes_pod_network_cidr is working only when value is 10.244.0.0/16

### ISSUE THREAD

**Issue by selmison** [geerlingguy/ansible-role-kubernetes#17]
The `kubernetes_pod_network_cidr` variable is accepting only the value of `10.244.0.0/16` since the parameter 
`Network` in  [kube-flannel.yml](https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml) is set in hardcoding to `10.244.0.0/16`

**Comment by geerlingguy** [comment]
Hmm, so it is. That's slightly annoying, but it looks like the fix is to just default to `10.244.0.0/16`, right?

**Comment by selmison** [comment]
That's it! The value of `kubernetes_pod_network_cidr` should always be `10.34.244.0.0/16`

**Comment by rodrigobrim** [comment]
Do the physical nodes (docker leader and workers) must be in this network (10.224.0.0/16)?

**Comment by geerlingguy** [comment]
Specifically see: https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L76

I hit this problem in a test build on centos7, I think, so I'm checking to see if this change fixes it.

**Comment by geerlingguy** [comment]
It looks like that test build failure _might_ be related to #20. D'oh! Kubernetes 1.12 seems to have snuck in non-stable, and is causing me some grief :P

**Comment by geerlingguy** [comment]
Yep! Fixed in 0bb0604 (test failure is unrelated).

**Comment by zzaareer** [comment]
Thank you. its working find when i used the following command :
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/32a765fd19ba45b387fdc5e3812c41fff47cfd55/Documentation/kube-flannel.yml
