### ISSUE TITLE
Swap is not removed in the role

### ISSUE THREAD

**Issue by rodrigobrim** [geerlingguy/ansible-role-kubernetes#21]
Hello Jeff. I'm continuing my saga 🗡

Now, I've noticed that the role don't remove the swap, so the playbook fails when deploying the flannel.

Thank you for the support.

**Comment by geerlingguy** [comment]
There's a role for that™

https://github.com/geerlingguy/ansible-role-swap

See, for example, how I use that role in my [Raspberry Pi Dramble](https://github.com/geerlingguy/raspberry-pi-dramble/blob/3.0.1/main.yml#L32-L33) project.

This role assumes you have either already taken care of swap disabling in your playbook or on your servers, or you have the `--fail-swap-on=false` option in your kubernetes settings so it ignores swap being present.
