### ISSUE TITLE
seperate [etcd]  and more than one master is possible?

### ISSUE THREAD

**Issue by dimthe** [geerlingguy/ansible-role-kubernetes#25]
Hello

for a multi node set up is it possible to edit the role to have 2 masters and few nodes running etcd ?

**Comment by geerlingguy** [comment]
Right now, no; this role intentionally _only_ supports one master. In the future that may change, but I would recommend going with kubespray or a hosted service if you want to have multiple masters at this time.

**Comment by stephenwithav** [comment]
I came to ask this exact same question.

I'll try a single-master for now, then see if I need redundancy.
