### ISSUE TITLE
[FEATURE] Append `kubernetes_ignore_preflight_errors` to the join command

### ISSUE THREAD

**Issue by Tomsons** [geerlingguy/ansible-role-kubernetes#27]
As stated in the title, it would be great to also append `kubernetes_ignore_preflight_errors` to the join commands executed on the worker nodes

**Comment by DamnedNForsaken** [comment]
@Tomsons I believe that you are refereeing to this issue:
https://github.com/kubernetes/kubeadm/issues/975

I have tried both with u16 & centos7 machines and now always have the following failure, in task:

Join node to Kubernetes master

`[WARNING RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs_wrr ip_vs_sh ip_vs ip_vs_rr] or no builtin kernel ipvs support: map[nf_conntrack_ipv4:{} ip_vs:{} ip_vs_rr:{} ip_vs_wrr:{} ip_vs_sh:{}]`

**Comment by Tomsons** [comment]
@DamnedNForsaken I don't refer to this issue. On Debian9 (stretch), the preflight checks complain about an unsupported docker version, which is currently at `Docker version 18.09.0, build 4d60db4`. Ignoring this preflight check at `kubeadm init` works perfectly but crashes when it comes to the join command of the worker nodes. I just cloned and patched this repo to append the preflight ignore flags to the join command and it worked like a charm for a brand new cluster from scratch

**Comment by DamnedNForsaken** [comment]
@Tomsons
I believe that this all stems from the same issue. See a more complete output from the failure of that task.

`stderr: |2-
            [WARNING RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh] or no builtin kernel ipvs support: map[ip_vs:{} ip_vs_rr:{} ip_vs_wrr:{} ip_vs_sh:{} nf_conntrack_ipv4:{}]
    you can solve this problem with following methods:
     1. Run 'modprobe -- ' to load missing kernel modules;
    2. Provide the missing builtin kernel ipvs support
  
    I1127 15:25:48.385472   19188 kernel_validator.go:81] Validating kernel version
    I1127 15:25:48.385612   19188 kernel_validator.go:96] Validating kernel config
    [preflight] Some fatal errors occurred:
            [ERROR SystemVerification]: unsupported docker version: 18.09.0
    [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...``

**Comment by Tomsons** [comment]
Even if related, it doesn't make sense to have and ignore-preflight-errors arg on kubeadm init when the workers can't follow

**Comment by DamnedNForsaken** [comment]
Certainly. Well if you have a fix, which sounds like you have. Maybe you could put up a PR?

Though, I don't like the idea of ignoring all these errors for the record, and if the root cause of all this is due to the Docker version. It seems more prudent to pull in a tagged Docker version rather than just ignore the errors, right?

**Comment by rhino5oh** [comment]
@Tomsons Maybe you still want the ability to ignore preflight errors, but the solution to the error about an unsupported docker version is to ensure you have the proper, k8s supported version of docker on the machines you are trying to set up the cluster on. 

The latest release of geerlingguy.kubernetes installs kubernetes 1.11 by default, which I believe only supports docker 17.03.  Support for Docker 18.xx isn't availble until you get to k8s 1.13 (I believe).

If you're chaining together geerlingguy.docker to install docker first, and then following it up with geerlingguy.kubernetes afterwards to set up the cluster, simply specify version 17.03 of Docker to install when calling geerlingguy.docker.  For example:

      # prevents yum from automatically trying to install latest version of
      # docker (even when you specify 17.03) on redhat machines, because yum
      # considers 17.03 to be 'obsoleted'
      - name: Setting obsoletes=0 in /etc/yum.conf
        lineinfile:
          path: "/etc/yum.conf"
          state: 'present'
          regexp: 'obsoletes=.*'
          line: 'obsoletes=0'
          insertafter: '[main]'
        when: ansible_os_family == 'RedHat'

      # Set variable for Docker 17.03 on redhat machines
      - set_fact:
          docker_version: "docker-ce-17.03.3.ce"
        when: ansible_os_family == 'RedHat'

      # Set variable for Docker 17.03 on debian machines
      - set_fact:
          docker_version: "docker-ce=17.03.3~ce-0~ubuntu-xenial"
        when: ansible_os_family == 'Debian'

      # Install Docker, using variable for version 17.03
      - name: "Running geerlingguy.docker role"
        include_role:
          name: geerlingguy.docker
        vars:
          docker_package: "{{ docker_version }}"

      - name: "Running geerlingguy.kubernetes role"
        include_role:
          name: geerlingguy.kubernetes

**Comment by geerlingguy** [comment]
I was going to say I already have this configurable, then I realized you mention adding it to the `join` command on the nodes. I will definitely consider doing that, as that would make sense (the same setting applying to both master and nodes).

**Comment by moikot** [comment]
Please add the option. My join command fails with
```
fatal: [192.168.88.248]: FAILED! => {"changed": true, "cmd": "kubeadm join 192.168.88.247:6443 --token gx4u2a.dz0oqkepvhmelj4c     --discovery-token-ca-cert-hash sha256:ecdfc...78c9 ", "delta": "0:00:01.206068", "end": "2019-07-28 10:16:27.010006", "msg": "non-zero return code", "rc": 1, "start": "2019-07-28 10:16:25.803938", "stderr": "\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\n\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.1. Latest validated version: 18.09\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Swap]: running with swap on is not supported. Please disable swap\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", ...
```

**Comment by moikot** [comment]
Please add kubernetes_ignore_preflight_errors for join operations. I'm installing with swap enabled and on **join** I'm getting (master is fine).
```shell
...
[ERROR Swap]: 
running with swap on is not supported. Please disable swap
...
```
