### ISSUE TITLE
Stuck at "Join node to Kubernetes master"

### ISSUE THREAD

**Issue by papanito** [geerlingguy/ansible-role-kubernetes#34]
I have a 3-nodes setup - 1 master node, 2 worker nodes. The ansible playbook stucks at the following taks
```
TASK [ansible.kubernetes : Join node to Kubernetes master]
```
means it just stays there and does not continue

If I check on the worker node, apparently the kubelet service does not start up
```
Dec 27 22:45:01 worker2 kubelet[15002]: I1227 22:45:01.557815   15002 server.go:407] Version: v1.13.1
Dec 27 22:45:01 worker2 kubelet[15002]: I1227 22:45:01.558328   15002 plugins.go:103] No cloud provider specified.
Dec 27 22:45:01 worker2 kubelet[15002]: F1227 22:45:01.558412   15002 server.go:261] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Dec 27 22:45:01 worker2 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Dec 27 22:45:01 worker2 systemd[1]: kubelet.service: Unit entered failed state.
Dec 27 22:45:01 worker2 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```
So the file is missing: ` /etc/kubernetes/bootstrap-kubelet.conf` and I do not entirely understand how the file should be where it is expected? Is it part of the kubernetes package or shall it come from the ansible role as template?

**Comment by papanito** [comment]
Any suggestions how to proceed?

**Comment by jose-sanchezm** [comment]
Hello, were you able to solve this? I'm stuck at the same point.

**Comment by papanito** [comment]
Yes I have and it's not a bug but me. After initially applying the role I ended in #30. After this problem was solved, the following happened

I've tried to use the correct package resource for my debian so I've set
```
- kubernetes_apt_repository: "deb http://apt.kubernetes.io/ kubernetes-stretch {{ kubernetes_apt_release_channel }}"
```
It turned out that reapplying the role does only add the new package source so `/etc/apt/sources.list.d/apt_kubernetes_io.list` looked like this
```
deb http://apt.kubernetes.io/ kubernetes-stretch main
deb http://apt.kubernetes.io/ kubernetes-xenial main
```
Unfortunately the [`kubernetes-stretch`](https://packages.cloud.google.com/apt/dists/kubernetes-stretch/main/binary-amd64/Packages) does only contain `kubelet` and not `kubeadm` which does the [bootstrapping](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/). So removing `apt_kubernetes_io.list` and switching back to `kubernetes-xenial` solved this problem.
