### ISSUE TITLE
Failure on kubeadm join - "The IPVS proxier will not be used"

### ISSUE THREAD

**Issue by rhino5oh** [geerlingguy/ansible-role-kubernetes#38]
I use this role pretty regularly in a continuous integration pipeline that I have.  For some reason, I get this error intermittently.  I don't know of an exact way to reproduce it.  It just seems to happen randomly:

<img width="1318" alt="screen shot 2019-02-08 at 8 53 03 pm" src="https://user-images.githubusercontent.com/4404630/52514939-254f4280-2be4-11e9-9e20-1c96fcc69d56.png">

It honestly seems like more of a kubeadm issue than an issue with your particular role, however I can't say for certain.  Maybe there's a way to catch the error in this role, and respond appropriately?  The error does give some suggestions on what to try.  

For the particular screenshot I provided, its a 3 node cluster - 1 master and 2 workers.  All nodes are CentOS 7.

**Comment by rhino5oh** [comment]
A little more context here:  https://github.com/kubernetes/kubeadm/issues/975

**Comment by bart0sh** [comment]
@rhino5oh

> For some reason, I get this error intermittently. I don't know of an exact way to reproduce it. It just seems to happen randomly:

Exact way to reproduce it is to do ```echo 0 > /proc/sys/net/bridge/bridge-nf-call-iptables``` I guess.

If you want to fix it you should ensure that /proc/sys/net/bridge/bridge-nf-call-iptables is set to 1. You can do it by adding ```net.bridge.bridge-nf-call-iptables = 1``` line to /etc/sysctl.conf or by setting net.bridge.bridge-nf-call-iptables in your task, e.g. [like this](https://github.com/kubernetes-sigs/kubespray/blob/master/roles/kubernetes/node/tasks/main.yml#L86)

**Comment by rhino5oh** [comment]
I'm a little confused.  It seems odd to me that I would be expected to do anything (or geerlingguy's role for that matter). We're simply doing a 'kubeadm join' command and it fails.  There's nothing that implies a user needs to manually append something to a file or add an entry to iptables in order to get 'kubeadm join' to work.  Your solution may fix the issue, but it seems like a workaround to the real issue.

**Comment by bart0sh** [comment]
Yes, you're simply doing 'cubed join' and it fails with the error message explaining why it failed. You may have missed the message, I guess. It starts with [ERROR] prefix.

**Comment by jose-sanchezm** [comment]
This is clearly stated in the documentation at https://kubernetes.io/docs/setup/independent/install-kubeadm/ specially for Red Hat derivatives. I will write a script to prepare my nodes in case they run CentOS but I think this should be taken care of by the role itself.
