### ISSUE TITLE
Configure Flannel networking

### ISSUE THREAD

**Issue by xgy560501** [geerlingguy/ansible-role-kubernetes#51]
(item=kubectl apply -f /tmp/kac.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["kubectl", "apply", "-f", "/tmp/kac.yml"], "delta": "0:00:00.330669", "end": "2019-06-13 16:09:26.484968", "item": "kubectl apply -f /tmp/kac.yml", "msg": "non-zero return code", "rc": 1, "start": "2019-06-13 16:09:26.154299", "stderr": "error: the path \"/tmp/kac.yml\" does not exist", "stderr_lines": ["error: the path \"/tmp/kac.yml\" does not exist"], "stdout": "", "stdout_lines": []}

**Comment by mikev1963** [comment]
I get the following error:
failed: [kube1] (item=kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["kubectl", "apply", "-f", "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml"], "delta": "0:00:00.375162", "end": "2019-08-03 19:33:08.173254", "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml", "msg": "non-zero return code", "rc": 1, "start": "2019-08-03 19:33:07.798092", "stderr": "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://192.168.1.61:6443/api?timeout=32s: dial tcp 192.168.1.61:6443: connect: connection refused\nunable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://192.168.1.61:6443/api?timeout=32s: dial tcp 192.168.1.61:6443: connect: connection refused", "stderr_lines": ["unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://192.168.1.61:6443/api?timeout=32s: dial tcp 192.168.1.61:6443: connect: connection refused", "unable to recognize \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\": Get https://192.168.1.61:6443/api?timeout=32s: dial tcp 192.168.1.61:6443: connect: connection refused"], "stdout": "", "stdout_lines": []}

**Comment by sergeyjsg** [comment]
Sorry, any update for this issue? Got same error as in above message: 
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml": Get https://192.168.0.22:6443/api?timeout=32s: dial tcp 192.168.0.22:6443: connect: connection refused

**Comment by georgms** [comment]
Me too, version 3.0.1

**Comment by georgms** [comment]
I could fix this using:

```yaml
  vars:
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"
```

This is actually mentioned in the [documentation of the role](https://galaxy.ansible.com/geerlingguy/kubernetes). More info about swap space is provided in this [kubeadm issue](https://github.com/kubernetes/kubeadm/issues/610).

**Comment by geerlingguy** [comment]
It looks like there are a few different issues here:

```
/tmp/kac.yml" does not exist
```

Not sure what that's for, but it's not related to this role (this role doesn't have that string in it anywhere).

```
Get https://192.168.1.61:6443/api?timeout=32s
```

That's not necessarily related to flannel installation—I would suggest looking at `kubelet`'s logs to see what's happening (e.g. `journalctl -u kubelet`).

```
--fail-swap-on=false
```

That may very well be the case for those not being able to connect to the K8s API—which is why it's important to check `kubelet`'s logs :)
