### ISSUE TITLE
Not installing dashboard if the cluster is running

### ISSUE THREAD

**Issue by moikot** [geerlingguy/ansible-role-kubernetes#57]
I forgot to enable the dashboard and tried to run the role again. I got this:

```shell
TASK [geerlingguy.kubernetes : Check if Kubernetes Dashboard UI service already exists.] *******************************
ok: [192.168.88.247]

TASK [geerlingguy.kubernetes : Enable the Kubernetes Web Dashboard UI (if configured).] ********************************
skipping: [192.168.88.247]
```

When I run the command manually, I get nothing, obviously because there is no dashboard running.
```
kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
```

**Comment by moikot** [comment]
That could be. But don't you think that Step "Check if Kubernetes Dashboard UI service already exists." never fails because it has "failed_when: false" therefore step "Enable the Kubernetes Web Dashboard UI (if configured)." is always steeped.

**Comment by ernestomedina17** [comment]
Work Around: Override the variable

`kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml`

[Reference](https://github.com/kubernetes/dashboard/releases)
