### ISSUE TITLE
kubectl fails if you run it twice in Ansible

### ISSUE THREAD

**Issue by jamesla** [geerlingguy/ansible-role-kubernetes#6]
If you run this playbook twice you will get a failure on anything that invokes kubectl (refused to connect to host). However fine the first time this playbook runs. 

A quick search shows that other people on the internet have seen this behaviour with kubectl and Ansible. For now I am just using ignore_error: true on those tasks.

**Comment by geerlingguy** [comment]
Strange... I haven't had this issue if I use `become: yes` at least, as the `kubectl` connection config should work for the root user. I've only tested within Docker, a VirtualBox environment, and on a Pi cluster so far; haven't tested in EC2, DigitalOcean etc.
