### ISSUE TITLE
I see kubernetes-admin

### ISSUE THREAD

**Issue by kovkev** [geerlingguy/ansible-role-kubernetes#62]
I see a `kubernetes-admin` user in the `/etc/kubernetes/admin.conf` file.

I was wondering if we should expect there to be a new user named `kubernetes-admin` in the provisioned image?

I don't see one on my provisioned image/machine. Should I create one manually? I might be misunderstanding that section of the kubeconfig file...

**Comment by geerlingguy** [comment]
I believe that is the user account which is used when connecting to the Kubernetes cluster itself over the API—it doesn't have any relationship to user accounts on the host that is running Kubernetes.

Read more about the kubeconfig file here: https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
