### ISSUE TITLE
No package matching 'kubelet-1.16.4-0' 

### ISSUE THREAD

**Issue by anilpanditi** [geerlingguy/ansible-role-kubernetes#66]
failed: [hdi_master1] (item={'name': 'kubelet-1.16.4-0', 'state': 'present'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "kubelet-1.16.4-0", "state": "present"}, "msg": "No package matching 'kubelet-1.16.4-0' found available, installed or updated", "rc": 126, "results": ["No package matching 'kubelet-1.16.4-0' found available, installed or updated"]}
failed: [hdi_master1] (item={'name': 'kubectl-1.16.4-0', 'state': 'present'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "kubectl-1.16.4-0", "state": "present"}, "msg": "No package matching 'kubectl-1.16.4-0' found available, installed or updated", "rc": 126, "results": ["No package matching 'kubectl-1.16.4-0' found available, installed or updated"]}
failed: [hdi_master1] (item={'name': 'kubeadm-1.16.4-0', 'state': 'present'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "kubeadm-1.16.4-0", "state": "present"}, "msg": "No package matching 'kubeadm-1.16.4-0' found available, installed or updated", "rc": 126, "results": ["No package matching 'kubeadm-1.16.4-0' found available, installed or updated"]}
failed: [hdi_master1] (item={'name': 'kubernetes-cni', 'state': 'present'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "kubernetes-cni", "state": "present"}, "msg": "No package matching 'kubernetes-cni' found available, installed or updated", "rc": 126, "results": ["No package matching 'kubernetes-cni' found available, installed or updated"]

**Comment by geerlingguy** [comment]
@anilpanditi - Can you give more context as to how this failure occurred? Are you using this role on a CentOS or Red Hat server, or Amazon Linux? Some other system? The CI tests are passing, so at least I know that CentOS repos contain those versions. I can't get the same error that you're seeing to happen.
