### ISSUE TITLE
Playbook is not working

### ISSUE THREAD

**Issue by george74greece** [geerlingguy/ansible-role-kubernetes#70]
Dear all,

I am trying to execute the default yml playbook (test.yml) you have but i have the following error: 
Can you please advice?

************
command:
*************
[root@desktop-2g9ao3g geerlingguy.kubernetes]# ansible-playbook test.yml --extra-vars "ansible_ssh_user=root ansible_ssh_pass=1234567"

************
error:
************
ERROR! the role 'geerlingguy.docker' was not found in /root/.ansible/roles/geerlingguy.kubernetes/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root/.ansible/roles/geerlingguy.kubernetes

The error appears to be in '/root/.ansible/roles/geerlingguy.kubernetes/test.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - geerlingguy.docker
      ^ here

*************
yml file:
*************
[root@desktop-2g9ao3g geerlingguy.kubernetes]# cat test.yml
- hosts: all

  vars:
    kubernetes_allow_pods_on_master: true

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
[root@desktop-2g9ao3g geerlingguy.kubernetes]#

Thanks,
George

**Comment by geerlingguy** [comment]
If you want to use that playbook you need to install it's dependencies with Ansible Galaxy first. See the requirements file in the molecule default directory.

**Comment by itJunky** [comment]
@geerlingguy can you explain procedure of install dependencies?

I'll try it, but get same error "ERROR! the role 'geerlingguy.docker' was not found"

```
> ansible-galaxy role install -r molecule/default/requirements.yml
Starting galaxy role install process
- downloading role 'containerd', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-containerd/archive/1.4.0.tar.gz
- extracting geerlingguy.containerd to /home/a/.ansible/roles/geerlingguy.containerd
- geerlingguy.containerd (1.4.0) was installed successfully
a@ansible ~/k/cluster_setup (master)> ansible-galaxy collection install -r molecule/default/requirements.yml
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
a@ansible ~/k/cluster_setup (master)> ansible-playbook playbook.yml --extra-vars "target_master=k8s-masters" --extra-vars "target_node=k8s-nodes"
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! the role 'geerlingguy.docker' was not found in /home/a/k8s/cluster_setup/roles:/home/a/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/a/k8s/cluster_setup

The error appears to be in '/home/a/k8s/cluster_setup/playbook.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - geerlingguy.docker
      ^ here
a@ansible ~/k/cluster_setup (master) [1]> 

```
