### ISSUE TITLE
Multiple K8s masters for high-availability

### ISSUE THREAD

**Issue by xidam27** [geerlingguy/ansible-role-kubernetes#76]
Would it be possible to extend an existing cluster created via this role with an additional master to have HA control-plane without major disruption to currently running services?

I'm looking at the official guide [Creating Highly Available clusters with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/) but it looks like I need to re-initialise the master. Thanks for your suggestions.

**Comment by geerlingguy** [comment]
It's something I'd be open to exploring but I do believe it's easier (if not only possible) to do it when you build the cluster initially.
