### ISSUE TITLE
kubernetes_pod_network is not set correctly when calico cni used

### ISSUE THREAD

**Issue by elcomtik** [geerlingguy/ansible-role-kubernetes#81]
I have set following vars to configure subnet for pods:
```
kubernetes_pod_network:
  cni: 'calico'
  cidr: '10.11.0.0/16'
```
However it gets default subnet 192.168.0.0/16

I looked to cluster info and there it looks to be set correctly:
```
$ kubectl cluster-info dump | grep cidr
                            "--allocate-node-cidrs=true",
                            "--cluster-cidr=10.11.0.0/16",
                            "--node-cidr-mask-size=24",
```

I looked at calicoctl for pools, and there it is not ok
```
$ calicoctl get ippool -o wide
NAME                  CIDR             NAT    IPIPMODE   VXLANMODE   DISABLED   SELECTOR   
default-ipv4-ippool   192.168.0.0/16   true   Always     Never       false      all()  
```

I have very little experience with setting up k8s cluster, so I have absolutely no idea what is wrong with this role.

**Comment by zx1986** [comment]
The problem is: the CIDR value is writing in https://docs.projectcalico.org/v3.10/manifests/calico.yaml

**Comment by zx1986** [comment]
refs: https://github.com/geerlingguy/ansible-role-kubernetes/issues/86

**Comment by elcomtik** [comment]
Still not solved

**Comment by rdxmb** [comment]
crosslink: https://github.com/geerlingguy/ansible-role-kubernetes/issues/86#issuecomment-1302780074

imho this can be closed
