### ISSUE TITLE
Calico manifest & pod cidr

### ISSUE THREAD

**Issue by lvincens** [geerlingguy/ansible-role-kubernetes#86]
The default calico manifest in the role https://docs.projectcalico.org/v3.10/manifests/calico.yaml actually enforces the pod cidr to 
192.168.0.0/16 which may cause issues when overriding the cidr with kubeadm.

``` yaml
kubernetes_pod_network:
  cni: 'calico'
  cidr: '10.10.0.0/16'
```

The official documentation actually talks about this topic: https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises

As a fix, the following manifest should be used: 
```
https://docs.projectcalico.org/manifests/calico.yaml
```

As a workaround, it is possible to override the kubernetes_calico_manifest_file variable in your inventory:

``` yaml
kubernetes_calico_manifest_file: https://docs.projectcalico.org/manifests/calico.yaml
```

Best regards,

**Comment by rdxmb** [comment]
if you use https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/defaults/main.yml#L28-L29 in your variables, this should be correct. Isn't it?

@lvincens 

You cannot overwrite the ip calico is using with this role. However, you should set the ip **calico wants to have** when running `kubeadm init` :)
