### ISSUE TITLE
Drop support for Docker runtime (in favor of containerd?)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-kubernetes#88]
See: https://twitter.com/Dixie3Flatline/status/1334188919215116291

Basically, Kubernetes 1.20 and on are going to drop support for Docker as the container runtime on nodes—so it would be best to switch to something like containerd or CRI-O.

**Comment by geerlingguy** [comment]
It doesn't technically affect the way this role works, but the tests would need to be updated to drop docker: https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/molecule/default/converge.yml#L28

**Comment by sculley** [comment]
+1 for containerd

**Comment by Spirit-act** [comment]
+1 CRI-O

**Comment by geerlingguy** [comment]
Related: https://github.com/geerlingguy/raspberry-pi-dramble/issues/187

**Comment by learmond** [comment]
+1 for containerd

**Comment by efo1291** [comment]
Containerd

**Comment by rdxmb** [comment]
I already run this role together with https://github.com/geerlingguy/ansible-role-containerd, which works very fine. However, the cgroup driver should be changed to `systemd`. Probably this should be done with https://github.com/geerlingguy/ansible-role-containerd/issues/2

**Comment by ambled** [comment]
+1

**Comment by geerlingguy** [comment]
See latest commit, linked above.
