### ISSUE TITLE
project not working on centos 6

### ISSUE THREAD

**Issue by cloudman1978** [geerlingguy/ansible-role-kubernetes#95]
TASK [geerlingguy.kubernetes : Configure Flannel networking.] ******************************************************************************************************************************
failed: [master] (item=kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["kubectl", "apply", "-f", "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml"], "delta": "0:00:00.059596", "end": "2021-02-19 10:11:30.970859", "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml", "msg": "non-zero return code", "rc": 1, "start": "2021-02-19 10:11:30.911263", "stderr": "The connection to the server XXXXX:6443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server XXXXX:6443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
failed: [master] (item=kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["kubectl", "apply", "-f", "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"], "delta": "0:00:00.057774", "end": "2021-02-19 10:11:31.848306", "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml", "msg": "non-zero return code", "rc": 1, "start": "2021-02-19 10:11:31.790532", "stderr": "The connection to the server XXXXXX:6443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server XXXXX:6443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

**Comment by geerlingguy** [comment]
@cloudman1978 - CentOS 6 was EOL in November 2020, and I don't offer any support for it in any of my projects anymore.
